package com.model;
// Generated 2018-02-14 00:36:07 by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import javax.persistence.*;

/**
 * AktualizacjaDanych generated by hbm2java
 */
@Entity
@Table(name="aktualizacja_danych"
    ,schema="public"
)
@JsonIdentityInfo(scope = AktualizacjaDanych.class,generator = ObjectIdGenerators.PropertyGenerator.class , property = "idAktualData") 

public class AktualizacjaDanych  implements java.io.Serializable {


     private Long idAktualData;
     
     private Dzialki dzialki;
     private int nrAktualizacji;
     private String dataAktualizacji;
     private String sposobPrzekazaniaDanychDoAktualizacji;
     private String zaktualizowaneDane;

    public AktualizacjaDanych() {
    }

	
    public AktualizacjaDanych(Long idAktualData, Dzialki dzialki, int nrAktualizacji) {
        this.idAktualData = idAktualData;
        this.dzialki = dzialki;
        this.nrAktualizacji = nrAktualizacji;
    }
    public AktualizacjaDanych(Long idAktualData, Dzialki dzialki, int nrAktualizacji, String dataAktualizacji, String sposobPrzekazaniaDanychDoAktualizacji, String zaktualizowaneDane) {
       this.idAktualData = idAktualData;
       this.dzialki = dzialki;
       this.nrAktualizacji = nrAktualizacji;
       this.dataAktualizacji = dataAktualizacji;
       this.sposobPrzekazaniaDanychDoAktualizacji = sposobPrzekazaniaDanychDoAktualizacji;
       this.zaktualizowaneDane = zaktualizowaneDane;
    }
   
     @Id 

    @SequenceGenerator(name="Aktualizacja_danych_id_seq",
                       sequenceName="Aktualizacja_danych_id_seq",
                       allocationSize=1)
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
                    generator="Aktualizacja_danych_id_seq")

    @Column(name="id_aktual_data", unique=true, nullable=false)
    public Long getIdAktualData() {
        return this.idAktualData;
    }
    
    public void setIdAktualData(Long idAktualData) {
        this.idAktualData = idAktualData;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nr_dzialki", nullable=false)
    public Dzialki getDzialki() {
        return this.dzialki;
    }
    
    public void setDzialki(Dzialki dzialki) {
        this.dzialki = dzialki;
    }

    
    @Column(name="nr_aktualizacji", nullable=false)
    public int getNrAktualizacji() {
        return this.nrAktualizacji;
    }
    
    public void setNrAktualizacji(int nrAktualizacji) {
        this.nrAktualizacji = nrAktualizacji;
    }

    
    @Column(name="data_aktualizacji")
    public String getDataAktualizacji() {
        return this.dataAktualizacji;
    }
    
    public void setDataAktualizacji(String dataAktualizacji) {
        this.dataAktualizacji = dataAktualizacji;
    }

    
    @Column(name="sposob_przekazania_danych_do_aktualizacji")
    public String getSposobPrzekazaniaDanychDoAktualizacji() {
        return this.sposobPrzekazaniaDanychDoAktualizacji;
    }
    
    public void setSposobPrzekazaniaDanychDoAktualizacji(String sposobPrzekazaniaDanychDoAktualizacji) {
        this.sposobPrzekazaniaDanychDoAktualizacji = sposobPrzekazaniaDanychDoAktualizacji;
    }

    
    @Column(name="zaktualizowane_dane")
    public String getZaktualizowaneDane() {
        return this.zaktualizowaneDane;
    }
    
    public void setZaktualizowaneDane(String zaktualizowaneDane) {
        this.zaktualizowaneDane = zaktualizowaneDane;
    }




}


